<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;

function sports_module_theme($existing, $type, $theme, $path) {
    return [
        'sports_group_tree' => [
            'variables' => [
                'groups' => ''
            ]
        ],
        'sports_group_link' => [
            'variables' => [
                'url' => '',
                'title' => ''
            ]
        ]
    ];
}

function sports_module_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $result = AccessResult::neutral();
  if ($field_definition->getName() == 'field_popularity') {
    if ($operation == 'edit' && !in_array('administrator', $account->getRoles())) {
      $result = AccessResult::forbidden();
    }
  }
  return $result->addCacheContexts(['user.roles:administrator']);
}