_core:
  default_config_hash: cjVezXXYut3s9F0USO01VYYEePZcdF3UKTqUiH35rng
log_level: 3
documentation_domain: 'https://ecaguide.org'
user: ''
dependency_calculation:
  - bundle
  - field_storage
  - field_config
  - new_field_config
