_core:
  default_config_hash: nRysvGldi9bVjwAPJlKXm9C8exWIT4hQhVYJPgYTCWI
favicon:
  mimetype: image/png
  path: themes/custom/tailwind_sports/icons/bb-pixa-192.png
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: themes/custom/tailwind_sports/icons/bb-pixa-192.png
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: auto
classic_toolbar: horizontal
secondary_toolbar_frontend: true
high_contrast_mode: false
accent_color: ''
focus_color: ''
layout_density: ''
show_description_toggle: false
show_user_theme_settings: false
