pusher_api_channel: pusher_api
enable_node: 'yes'
node_type_article_create: 0
node_type_article_update: 0
node_type_article_delete: 0
node_type_article_channel: article
node_type_game_create: 0
node_type_game_update: 1
node_type_game_delete: 0
node_type_game_channel: sp0rts-comments
node_type_game_recap_create: 0
node_type_game_recap_update: 0
node_type_game_recap_delete: 0
node_type_game_recap_channel: game_recap
node_type_highlight_create: 0
node_type_highlight_update: 0
node_type_highlight_delete: 0
node_type_highlight_channel: highlight
node_type_image_create: 0
node_type_image_update: 0
node_type_image_delete: 0
node_type_image_channel: image
node_type_link_create: 0
node_type_link_update: 0
node_type_link_delete: 0
node_type_link_channel: link
node_type_page_create: 0
node_type_page_update: 0
node_type_page_delete: 0
node_type_page_channel: page
node_type_podcast_episode_create: 0
node_type_podcast_episode_update: 0
node_type_podcast_episode_delete: 0
node_type_podcast_episode_channel: podcast_episode
node_type_reddit_post_create: 0
node_type_reddit_post_update: 0
node_type_reddit_post_delete: 0
node_type_reddit_post_channel: reddit_post
node_type_text_post_create: 0
node_type_text_post_update: 0
node_type_text_post_delete: 0
node_type_text_post_channel: text_post
node_type_tweet_create: 0
node_type_tweet_update: 0
node_type_tweet_delete: 0
node_type_tweet_channel: tweet
node_type_user_post_create: 0
node_type_user_post_update: 0
node_type_user_post_delete: 0
node_type_user_post_channel: user_post
node_type_webform_create: 0
node_type_webform_update: 0
node_type_webform_delete: 0
node_type_webform_channel: webform
node_type_youtube_video_create: 0
node_type_youtube_video_update: 0
node_type_youtube_video_delete: 0
node_type_youtube_video_channel: youtube_video
