_core:
  default_config_hash: qmqTJpMlE5WiRzfgUCghPZjdTTGQN3-fDTr4FcMGYXU
allowed_tags: '<a><b><em><strong><i><p>'
prefer_gravatar: '-1'
user_avatar_image_style: thumbnail
full_delete: 0
anon_default_avatar_fid: {  }
content_types:
  game: game
  article: 0
  game_recap: 0
  highlight: 0
  image: 0
  link: 0
  page: 0
  podcast_episode: 0
  reddit_post: 0
  text_post: 0
  tweet: 0
  user_post: 0
  webform: 0
  youtube_video: 0
comment_types:
  game_comments: game_comments
  comment: 0
