_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 066bb1c4-bd74-4a5e-8339-841b5fb91475
name: 'Untitled Sports Project'
mail: info@sp0rts.fans
slogan: ''
page:
  403: ''
  404: ''
  front: /node/164
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
