<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\group\Entity\Group;
use Drupal\node\Entity\Node;

function sports_importer_entity_update(EntityInterface $entity) {
  if ($entity->bundle() == 'tweet') {

    $account = strtolower($entity->get('field_tweet_author')->uri);
    $ids = \Drupal::entityQuery('group')
      ->condition('field_twitter_account', $account)
      ->execute();
    $group = Group::load(array_pop($ids));
    $type = 'group_node:' . $entity->getType();
    $node = Node::load($entity->id());

    $relation = $group->getContentByEntityId($type, $node->id());
    if (!$relation) {
      $group->addContent($node, $type);
    }
  }

}